### ISSUE TITLE
Wazuh-bosh agent 4.1.5 release

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh-bosh#12]
Hello team,

I am opening this issue to request the release of version 4.1.5 for bosh agents.

Best regards,

Alexander

**Comment by alberpilot** [comment]
Tasks: 
- [x] Create `4.1` branch from `master`.
- [x] Adapt `4.1` branch to use `4.1.5` Wazuh version.
- [x] Improve the README file in order to clarify the documentation.

**Comment by teddytpc1** [comment]
I have analyzed the procedure to setup the environment with Bosh. I am configuring a Bosh environment in order to test the procedure and creating a Ubuntu Xenial VM to generate the required blobs.
I will start to test tomorrow.

**Comment by teddytpc1** [comment]
I have generated the 4.1 branch, 4.1.5 packages, created the bosh environment for testing purposes and deployed the manager but if failed. Next week I will analyze why it failed and proceed to deploy the agent.

**Comment by teddytpc1** [comment]
Wasn't able to install the manager successfully on the Ubuntu stemcell. Will continue tomorrow.

**Comment by teddytpc1** [comment]
I was getting some errors when trying to install Wazuh Manager on /var/vcap. 
Now I have changed the directory to install on the default (/var/ossec).
With this issue resolved now I have to automate some changes in ossec.conf to properly configure Wazuh.

**Comment by teddytpc1** [comment]
Wazuh Manager deployment is configured and tested. I have made changes to:
- monitoring configuration.
- control configuration (start/stop).
- ossec.conf dynamic configuration of the NODE_IP. 

Will continue with the Agent deployment.

**Comment by teddytpc1** [comment]
I will attach some screenshots of the Manager deployment:
- Deploy
![Screenshot from 2021-07-21 10-52-58](https://user-images.githubusercontent.com/33964202/126500394-4daefcad-2f86-4324-83f3-26c1a68f0046.png)

- VM status:
![Screenshot from 2021-07-21 08-53-21](https://user-images.githubusercontent.com/33964202/126500445-6a9363d0-4a24-4e0f-b21d-0b0ea894a329.png)

- Delete Deployment:
![Screenshot from 2021-07-21 08-53-59](https://user-images.githubusercontent.com/33964202/126500506-f8bd7d86-e015-4195-b002-56ef28a57204.png)

**Comment by teddytpc1** [comment]
I have already made the configuration changes to deploy the Agent and tested it with a Nginx deployment:
- Deploy
![Screenshot from 2021-07-21 13-15-21](https://user-images.githubusercontent.com/33964202/126523195-eaeb8566-94d6-4587-85d6-bcb01ca51441.png)

- VM status:
![Screenshot from 2021-07-21 13-15-52](https://user-images.githubusercontent.com/33964202/126523287-ae91f1f0-887b-4edb-89ba-250fc31dac00.png)

- Process status:
![Screenshot from 2021-07-21 13-16-44](https://user-images.githubusercontent.com/33964202/126523379-a8d66537-a8d5-45c9-913c-66bb7464ac8d.png)

- Agent ossec.log
![Screenshot from 2021-07-21 13-17-28](https://user-images.githubusercontent.com/33964202/126523494-54834d60-56db-4499-86ee-80da9573c898.png)

- Delete deployment:
![Screenshot from 2021-07-21 13-25-01](https://user-images.githubusercontent.com/33964202/126524486-6cc6fbc5-24ae-4dbd-94d4-d86cdd24a2a1.png)

I will execute some additional tests.

**Comment by teddytpc1** [comment]
I have changed the way the manager NODE_IP is configured from:
`NODE_IP=ip -4 a show eth0 | grep inet | awk '{print $2}' | rev | cut -c4- | rev`
To:
`NODE_IP=<%= spec.ip %>`

**Comment by teddytpc1** [comment]
I have updated the README but is not completed yet. The delete section is yet to add.
Regarding the tests I have to validate the Wazuh multi-node cluster.

**Comment by teddytpc1** [comment]
In Branch **4.1** there is a stable version to deploy on a single node Manager.
I will be working in another branch to develop and test the cluster config.

**Comment by teddytpc1** [comment]
Bosh Cluster tests:

- VMs and process state. The nginx deployment contains the Wazuh Agent:
![Screenshot from 2021-07-22 16-26-19](https://user-images.githubusercontent.com/33964202/126698033-a21c6a26-d0c1-4907-a5ab-f4233820c5c8.png)

- Agent ossec.conf (cluster)
![Screenshot from 2021-07-22 16-25-43](https://user-images.githubusercontent.com/33964202/126697946-0be437a7-cb23-443c-a206-2ae789fb847b.png)

- Agent status
![Screenshot from 2021-07-22 16-25-03](https://user-images.githubusercontent.com/33964202/126697865-51e15494-43c8-4795-9d87-f1a3658c007f.png)

**Comment by teddytpc1** [comment]
I will update the documentation with the steps to deploy a Wazuh Cluster.

**Comment by teddytpc1** [comment]
README updated.

**Comment by teddytpc1** [comment]
Hi @abohorqu I have already created the release [v4.1.5](https://github.com/wazuh/wazuh-jenkins/releases/tag/v4.1.5).
