### ISSUE TITLE
Update Bosh to 4.2.4

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-bosh#16]
Hello team,

we need to update our Bosh repo to 4.2.4 to accommodate for our latest version.

Regards,

Javier.

**Comment by teddytpc1** [comment]
I have been working in this release. Had some issues with the source code compilation in Ubuntu Xenial. Several compilation test were ran and finally it was successfully built with Ubuntu Focal. 
Some changes were added to the repository files in order to adapt the scripts with the Wazuh changes from v4.1.5 to v4.2.x.
Tomorrow the deployment will be tested.

**Comment by teddytpc1** [comment]
The packages has been created and tested in a Ubuntu Xenial docker. They are being uploaded to the repository in branch `4.2.5`. Packages for `4.2.4` will be created tomorrow.
Both versions will be tested tomorrow in a Bosh environment.

**Comment by teddytpc1** [comment]
The deploy procedure has been redesigned:
- The blob files are no longer stored in the `wazuh-bosh` repository. They are stored in S3 instead.
- A new Dockerfile was added to generate the compiled source code for Ubuntu Xenial.
- A script to perform the compilation within the Docker container was also added.
- The `DEVELOPMENT.md` file was updated to specify how to use Docker to create the compressed files.
- The `README.md` was updated to reference the current version and update the procedure to download the compressed files from S3.

The procedure was tested and Wazuh Manager and Agent are being deployed successfully.
The compressed files are being uploaded to `packages-dev` S3 bucket.

A last test will be executed tomorrow.

**Comment by teddytpc1** [comment]
Release v4.2.5 is available.
Today the documentation and some scripts were corrected prior to the tag creation. The PR will be merged and the v4.2.4 release will created this afternoon.

**Comment by teddytpc1** [comment]
@havidarou, release v4.2.4 is available.
