### ISSUE TITLE
Users should bring their own certificates

### ISSUE THREAD

**Issue by jmcarp** [wazuh/wazuh-bosh#2]
The certificate and private key for `authd` are checked in at https://github.com/wazuh/wazuh-bosh/tree/master/jobs/wazuh-server/templates/config. These shouldn't be checked into source control; instead, users should be able to bring their own certificates via the server job spec. I'd be happy to submit a patch if this makes sense.

**Comment by snaow** [comment]
Hi @jmcarp,

Thanks for the feedback.
I agree, it does not make sense we provide an SSL certificates for `authd`.
We could either tell the user how to place its own certificates in the template/config folder, or pick them up from an external folder in the host by using server job spec.
What do you prefer?
Feel free to submit a patch, it will be very welcome.

Best,
Pedro.
