### ISSUE TITLE
Publish release to http://bosh.io/releases

### ISSUE THREAD

**Issue by jmcarp** [wazuh/wazuh-bosh#4]
This can be done by publishing a release someplace (github releases, s3, etc) and submitting a patch to https://github.com/bosh-io/releases.

**Comment by snaow** [comment]
That is an excellent idea.
We have an internal repository for Bosh we maany new changes to Bosh templates.
Please, let us update this repository to latest version (3.2.1) and we will generate and release and submit the patch to Bosh IO.

Thanks for helping us with the Bosh integration, any feedback will be welcome.

**Comment by LinuxBozo** [comment]
@snaow Just curious, do you have a timeline for getting updated to 3.2.1 here?

**Comment by snaow** [comment]
Hi @LinuxBozo @jmcarp 
3.2.1 version has been included.
I merged a bunch of improvements I had in a different repo.
Between others, I will say the major change is how the agents are registered:

In this version, the Bosh deployment won't fail even if the agent can't get a valid key from the Manager, the deployment will continue and return success.
A registration script will be in place and running, trying to get a valid key every 120 seconds, at the moment it gets a valid key, it will connect and start reporting.

This was done to prevent impact in others apps while you are deploying a Wazuh agent.

Any comments or ideas are very welcome, I did not test this last push so I appreciate any feedback you can give us.

Best regards,
Pedro.
