### ISSUE TITLE
git-lfs: Repository is over its data quota

### ISSUE THREAD

**Issue by Infra-Red** [wazuh/wazuh-bosh#8]
I'm getting the following error when trying to pull bosh blobs:
```
$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/wazuh/wazuh-bosh.git/info/lfs'
```

Could you please fix that? I'm not able to build release without blobs 🤷🏼‍♂️

**Comment by jm404** [comment]
Hi @Infra-Red ,

It seems that we reached our GIT LFS data quota which blocks users from downloading the blobs for Wazuh Manager and Agent.

We've uploaded them to S3 and updated the README.md instructions 946c7a98f83196552018dca816e1238c85700701 so you can easily download them.

Sorry for the inconvenience, let me know if you need further help.

Best regards,

Jose

**Comment by Infra-Red** [comment]
@jm404 Thanks for the help!
